spring.application.name=gestao
spring.datasource.url=jdbc:postgresql://localhost:5432/dbbordados
spring.datasource.username=postgres
spring.datasource.password=postgres
api.security.token.secret=V8y/B?E(G+KbP343ZZ9z$C&F)H@McFFFZr4u7x!A%D*G-KaPdRgUkXp
# Configurações de Upload de Arquivos (Multipart)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB