CREATE TYPE role_type AS ENUM ('EMPLOYEE', 'ADMIN');

CREATE TABLE EMPLOYEE(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    username VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    role role_type NOT NULL DEFAULT 'EMPLOYEE'
);
CREATE TABLE CUSTOMER(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(18) UNIQUE NOT NULL,
    address TEXT NOT NULL
);
