ALTER TABLE ORDER_COLORS
ADD CONSTRAINT FK_ORDER_COLORS_ORDER_ID FOREIGN KEY (order_id) REFERENCES ORDERS (id);

ALTER TABLE ORDER_SIZES
ADD CONSTRAINT FK_ORDER_SIZES_ORDER_ID FOREIGN KEY (order_id) REFERENCES ORDERS (id);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_CUSTOMER_ID FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(id);
